# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(error_messages={'unique': '用户名已重复'}, max_length=150, unique=True, verbose_name='用户名')),
                ('telephone', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='手机')),
                ('avatar_url', models.URLField(blank=True, max_length=255, verbose_name='头像链接')),
                ('register_source', models.CharField(default=0, max_length=10, verbose_name='注册来源')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户账号',
                'verbose_name_plural': '用户账号',
            },
        ),
    ]
